# build base mirror
  FROM alpine:3.14 AS base

  # set an environment variable
  ENV NODE_ENV=production \
      APP_PATH=/node/app
  
  # set work directory
  WORKDIR $APP_PATH

  # install node js and yarn
  RUN apk add --no-cache --update nodejs=14.17.4-r0 yarn=1.22.10-r0

# use the basal mirroring dependence phase
  FROM base AS install

  # copy package.json to work and directory
  COPY package.json ./

  # installation dependence
  RUN yarn

  # copy tsconfig.json to work and directory
  COPY tsconfig.json ./
  
  # copy src to work and directory
  COPY src ./

  # build
  RUN yarn build

  # remove typescript
  RUN yarn remove typescript

# in the final stage the image of the output is built in this stage and the front stage is a paving this stage
  FROM base

  # copying the node_modules folder generated by the copy depending stage to the working directory
  COPY --from=install $APP_PATH/node_modules ./node_modules

  # copying the package.json folder generated by the copy depending stage to the working directory
  COPY --from=install $APP_PATH/package.json ./package.json

  # copy all files in the current directory except for dockerignore copy into the mirror s working directory
  COPY --from=install $APP_PATH/dist ./dist

  # start up
  CMD yarn start
